diplomProject/shop/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from shopPlatform import views
from shopPlatform.views import GoodsListView, ShowGoods, ShowGoodsCategory, RezultSeach, AboutList, UserCabinet, editGoods,delGoods, \
    FinalBasket, delBG, ShowZakaz

urlpatterns = [
    path('', views.index, name='index'),
    path('about/',AboutList.as_view(),name='about' ),
    path('goodsCatalog/',GoodsListView.as_view(),name='listCatalog'),
    path('goodsCatalog/<int:pk>/', ShowGoods.as_view(), name='goodsCatalog'),
    path('category/<slug:slug>/',ShowGoodsCategory.as_view(), name='categoryGoods'),
    path('rezultSeach/',RezultSeach.as_view(), name='rezultSeach'),
    path('admin/', admin.site.urls),
    path('register/',views.register, name='register'),
    path('cabinet/',UserCabinet.as_view(), name='cabinet'),
    path('addGood/',views.addGood, name='addGood'),
    path('cabinet/editGoods/<int:id>/', views.editGoods,name='editGoods' ),
    path('cabinet/delete/<int:id>/', views.delGoods,name='delete' ),
    path('createComments/<int:id>', views.commentGoods, name='createComments'),
    #Корзина
    path('finalbasket/',FinalBasket.as_view(), name = 'finalBasket'),
    path('finalbasket/delete/<int:id>/', views.delBG,name='delBG' ),
    path('mybasket/<int:id>', views.mybasket, name='mybasket'),
    path('showZacaz/', ShowZakaz.as_view(), name='showZakaz'),
    ]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    ]

diplomProject/shop/shopPlatform/models.py
from django.db import models
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User, Group

# Create your models here.

#Модель категории товаров
class CategoryOfGoods(models.Model):
    nameOfCategory= models.CharField(max_length=100,verbose_name='Категория товара')
    slug = models.SlugField(max_length=100)
    def __str__(self):
        return self.nameOfCategory
    def get_absolute_url(self):
        return reverse('categoryGoods', kwargs={'slug':self.slug})
    class Meta:
        verbose_name = 'Категория товаров'
        verbose_name_plural = 'Категория товаров'

#Модель производитель товара
class Manufacturer(models.Model):
    nameOfFactory = models.CharField(max_length=150, verbose_name='Компания производитель')
    def __str__(self):
        return self.nameOfFactory
    def get_absolute_url(self):
        return reverse('man', kwargs={'man_id':self.pk})
    class Meta:
        verbose_name = 'Производитель товара'
        verbose_name_plural = 'Производитель товара'

#Модель товары
class Goods(models.Model):
    nameOfGoods = models.CharField(max_length=150, verbose_name='Название товара')
    priceOfGoods = models.IntegerField(verbose_name='Цена')
    manufacturerOfGoods = models.ForeignKey(Manufacturer,null=True,on_delete=models.CASCADE, verbose_name='Производитель товара')
    dateAppGoods = models.DateField(auto_now_add=True,verbose_name='Дата добавления в каталог')
    imageGoods = models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Каталог фото')
    categoryGoods = models.ForeignKey(CategoryOfGoods,null=True, on_delete=models.CASCADE, verbose_name='Категория товара')
    contexOfGoods = models.CharField(max_length=500,verbose_name='Описание товара')
    sellerGoods = models.ForeignKey(User,null=True, on_delete=models.CASCADE, verbose_name='Продавец товара')
    def __str__(self):
        return self.nameOfGoods
    def get_absolute_url(self):
        return reverse('goodsCatalog', kwargs={'pk':self.pk})
    class Meta:
        verbose_name_plural = 'Товары'

#Модель комментарии товаров
class CommentsOfGoods(models.Model):
    contextComment = models.CharField(max_length=250)
    idGoods = models.ForeignKey(Goods,null=True,blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null= True, blank=True, on_delete=models.CASCADE)
    class Meta:
        verbose_name_plural = 'Комментарии о товаре'

#Модель корзина покупок
class Basket(models.Model):
    zakazGuman = models.CharField(max_length=100)
    goodsZacaz = models.CharField(max_length=100, verbose_name='Название товара')
    countGoods = models.IntegerField(verbose_name='Кол-во товара')
    priceGoods = models.IntegerField(verbose_name='Цена за ед')
    sellerUser = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='Продавец товара')
    def __str__(self):
        valSum = self.priceGoods * self.countGoods
        return f'{valSum}'

diplomProject/shop/templates/shopTemplates/about.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center">Региональная площадка интернет-торговли SellAndBuy</h1>
<div class="blockAbout">
<p>
	"SellAndBuy" - полносервисная торговая платформа для продавцов и покупателей.
	На данный момент уже более {{goodsCount}} товаров по  {{catCount}} категориям!!!
</p>
<p>С нами работают уже более {{userGroup}} продавцов </p>
<p>Плюсы работы с нами:</p>
<ul class="list-group">
	<li class="list-group-item">Продавцу
		<ul>
			<li>Можете предоставить весь ваш ассортимент</li>
			<li>Минимальные затраты на продвижение товара</li>
			<li>Неограниченный объем на товарные позиции</li>
		</ul>
	</li>
	<li class="list-group-item">Покупателю
		<ul>
			<li>Огромный выбор продукции</li>
			<li>Оптовые цены</li>
		</ul>
	</li>
</ul>
<div class="contactInfo">
	<h4 class="text-center text-info">Контактная информация</h4>
	<address id="adr">Компания <strong>ООО "SellAndBuy" </strong>г.Новосибирск ул.Новосибирская 130 оф.13</address><br>
	<ul class="list-group">Контактные телефоны
		<li class="list-group-item">Секретарь  <a href="tel:+71234567890"> 8-(123)-456-78-90</a></li>
		<li class="list-group-item">Бухгалтерия  <a href="tel:+71234567890"> 8-(123)-456-78-99</a></li>
		<li class="list-group-item">Отдел маркетинга  <a href="tel:+71234567890"> 8-(123)-456-88-99</a></li>
		<li class="list-group-item">Отдел IT-разработки и сопровождения  <a href="tel:+71234567890"> 8-(123)-456-99-99</a></li>
	</ul>
	<ul class="list-group">Адрес электронной почты
		<li class="list-group-item"><a href="mailto:selltobuy@seller.ru">selltobuy@seller.ru</a></li>
	</ul>
</div>

</div>
{% endblock content %}

diplomProject/shop/templates/shopTemplates/addGood.html
{% extends 'base.html' %}

{% block content %}
<h3 class="text-center">Добавление товара в каталог</h3>
<form action="#" method="post" enctype="multipart/form-data" class="addGoods">
	{% csrf_token %}
	{% for i in form %}
	<div><p>{{i.label}}</p>  <p>{{i}}</p></div>
	{% endfor %}
	<button type="submit">Добавить в каталог</button>
</form>

{% endblock content %}

diplomProject/shop/templates/shopTemplates/createComments.html
{% extends 'base.html' %}

{% block content %}

<div class="col-md-12">
    <h4 class="text-center">Создать комментарий к товару {{goods}}</h4>
    <form action="#" method="POST" enctype="multipart/form-data" class="regForm">
        {% csrf_token %}
        {% for i in form %}
        <p>{{i}}</p>
        {% endfor %}
        

        <button type="submit" class="btn btn-success">Оставить комментарий</button>
    </form>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h4 class="text-center">{{good.nameOfGoods}}</h4>
            </div>
            <div class="panel-body">
                <div class="media">
                    <span class="pull-left"><img class="media-object goodPhotoDetail" src="{{ good.imageGoods.url }}"
                            alt="Нет фото"></span>
                    <div class="media-body">
                        <p>Цена: {{good.priceOfGoods}}</p>
                        <p>Категория: {{good.categoryGoods}}</p>
                        <p>Производитель: {{good.manufacturerOfGoods}}</p>
                        <p>Продавец: {{good.sellerGoods}}</p>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <p>{{good.contexOfGoods}}</p>
                <p>В продаже с: {{good.dateAppGoods}}</p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

diplomProject/shop/templates/shopTemplates/editGoods.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-12">
	<h4 class="text-center">Редактирование товара {{goods}}</h4>
	<form action="#" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{% for i in form %}	
			<p>{{i.label}}  {{i}} </p>
		{% endfor %}
		<button type="submit">Внести изменения</button>
	</form>
</div>



{% endblock content %}

diplomProject/shop/templates/shopTemplates/finalBasket.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h1 class="text-center">Корзина покупок</h1>
		</div>
	</div>
	<div class="col-md-12">
		<div class="flexBasket">
			<table class="table">
				<caption >Таблица заказа продавцам </caption>
				<thead>
				<tr>
					<th>Наименование</th>
					<th>Кол-во в заказе</th>
					<th>Цена за ед.</th>
					<th>Сумма</th>
					<th>Продавец</th>
					<th></th>
				</tr>
				</thead>
				{% for i in basket %}
				<tbody>
					<tr>
					<td>{{ i.goodsZacaz}}</td>
					<td>{{ i.countGoods}}</td>
					<td>{{ i.priceGoods}}</td>
					<td>{{ i }}</td>
					<td>{{ i.sellerUser }}</td>
					<td><button class="btn btn-warning"><a href="delete/{{ i.id }}">Удалить</a></button></td>
					</tr>
				</tbody>
				{% endfor %}
			</table>
		</div>
	</div>
</div>
{% endblock content %}

diplomProject/shop/templates/shopTemplates/goodDetail.html
{% extends 'base.html' %}
{% block title %}{{good.nameOfGoods}}{% endblock title %}
{% block content %}
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h4 class="text-center">{{good.nameOfGoods}}</h4>
			</div>
			<div class="panel-body">
				<div class="media">
					<span class="pull-left"><img class="media-object goodPhotoDetail" src="{{ good.imageGoods.url }}" alt="Нет фото"></span>
					<div class="media-body">
						<p>Цена: {{good.priceOfGoods}}</p>
						<p>Категория: {{good.categoryGoods}}</p>
						<p>Производитель: {{good.manufacturerOfGoods}}</p>
						<p>Продавец: {{good.sellerGoods}}</p>
						{% for group in request.user.groups.all %}
							{% if group.name == 'Покупатели' %}
						<div>
							<form action="{% url 'mybasket' good.id  %}" method="POST">
								{% csrf_token %}
								{{form}}
								<button type="submit" class="btn btn-success">Купить товар</button>
							</form>
						</div>
							{% endif %}
						{% endfor %}
					</div>
				</div>
			</div>
			<div class="panel-footer">
				<p>{{good.contexOfGoods}}</p>
				<p>В продаже с: {{good.dateAppGoods}}</p>
				<div class="addComments">
					{% for group in request.user.groups.all %}
					{% if group.name == 'Покупатели' %}
					<a href="{%  url 'createComments' good.id %}"><button class="btn btn-success">Добавить комментарий к товару</button></a>
					{% else %}
					<p>Для добавления комментария к товару - авторизуйтесь</p>
					{% endif %}
					{% endfor %}
				</div>
			</div>
			<div class="comments">
				<h3 class="text-center">Отзывы о товаре:</h3>
				{% for c in comments %}
				<div class="withComments">
					<p>Комментарий от: {{c.user}}</p>
					<p>{{c.contextComment}}</p>
				</div>
				{% empty %}
				<div class="withComments">
					<p>На данный момент отзывов о товаре нет.</p>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div>
{% endblock content %}

diplomProject/shop/templates/shopTemplates/goodsCatalog.html
{% extends 'base.html' %}

{% block content %}

{% for good in object_list %}
<div class="col-md-6 col-xs-12 col-sm-6 goodDiv">
	<a href="{{ good.get_absolute_url }}">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h4 class="text-center">{{good.nameOfGoods}}</h4>
		</div>
		<div class="panel-body">
			<div class="media">
				<span class="pull-left"><img  class="media-object goodPhoto" src="{{ good.imageGoods.url }}" alt="Нет фото"></span>
				<div class="media-body">
				<p>Цена: {{good.priceOfGoods}}</p>
				<p>Категория: {{good.categoryGoods}}</p>
				<p>Производитель: {{good.manufacturerOfGoods}}</p>
				<p>Продавец: {{good.sellerGoods}}</p>
				</div>
			</div>
		</div>
		<div class="panel-footer">
			<p>{{good.contexOfGoods}}</p>
			<p>В продаже с: {{good.dateAppGoods}}</p>
		</div>
	</div>
	</a>
</div>	
{% endfor %}
<div class="col-md-12">
	<div class="pagination">
		<span class="step-links">
			{% if page_obj.has_previous %}
			<a href="?page=1">Первая</a>
			<a href="?page={{ page_obj.previous_page_number }}">Предыдущая страница</a>
			{% endif %}

			<span class="current">
				Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
			</span>

			{% if page_obj.has_next %}
			<a href="?page={{ page_obj.next_page_number }}">Следующая страница</a>
			<a href="?page={{ page_obj.paginator.num_pages }}">Последняя страница</a>
			{% endif %}
		</span>
	</div>
</div>
{% endblock content %}

diplomProject/shop/templates/shopTemplates/goodsCategory.html
{% extends 'base.html' %}
{% block title %}{{category}}{% endblock title %}
{% block content %}
<h2 class="text-info text-center">Каталог товаров по группе {{category}}</h2>
<div class="row">
	<div class="col-md-12">
		{% for g in goods %}
		<div class="col-md-6 col-xs-12 col-sm-6 goodDiv">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h4 class="text-center"><a href="{{ g.get_absolute_url }}">{{g.nameOfGoods}}</a></h4>
				</div>
				<div class="panel-body">
					<div class="media">
						<span class="pull-left"><img class="media-object goodPhoto" src="{{ g.imageGoods.url }}"
								alt="Нет фото"></span>
						<div class="media-body">
							<p>Цена: {{g.priceOfGoods}}</p>
							<p>Категория: {{g.categoryGoods}}</p>
							<p>Производитель: {{g.manufacturerOfGoods}}</p>
							<p>Продавец: {{g.sellerGoods}}</p>
						</div>
					</div>
				</div>
				<div class="panel-footer">
					<p>{{g.contexOfGoods}}</p>
					<p>В продаже с: {{g.dateAppGoods}}</p>
				</div>
			</div>
		</div>
		{%  empty %}
		<p>Товаров в данной категории нет в наличие</p>
		{% endfor %}
	</div>
</div>
<div class="col-md-12">
	<div class="pagination">
		<span class="step-links">
			{% if page_obj.has_previous %}
			<a href="?page=1">Первая</a>
			<a href="?page={{ page_obj.previous_page_number }}">Предыдущая страница</a>
			{% endif %}

			<span class="current">
				Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
			</span>

			{% if page_obj.has_next %}
			<a href="?page={{ page_obj.next_page_number }}">Следующая страница</a>
			<a href="?page={{ page_obj.paginator.num_pages }}">Последняя страница</a>
			{% endif %}
		</span>
	</div>
{% endblock content %}

diplomProject/shop/templates/shopTemplates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<div class="seach">
		<h2 class="text-center text-info">Поиск по каталогам</h2>
			<form action="{% url 'rezultSeach' %}" method="get" class="form-inline" role="form" autocomplete="off">
			{% csrf_token %}
			<div class="seachBlock">
			{{formSeach}}
			<button type="submit" class="btn btn-primary btn-lg ">Поиск товара</button>
			</div>
			</form>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
	{% for c in listCategory %}
	<div class="row rowGoods">
	<div class="col-md-4"><h3>{{ c.nameOfCategory }}</h3></div>
	<div class="col-md-12 lineDiv"><hr></div>
	</div>
	<div class="row rowFlex">
		{% for el in c.goods_set.all %}
		<div class="col-md-4 col-sm-6 goodsPanel">
			<a href="{{ el.get_absolute_url }}">
			<p class="pImg"><img src="{{ el.imageGoods.url }}" alt="Фото товара" class="goodPhoto"></p>
			<p class="text-success">{{ el.nameOfGoods }}</p>
			<p class="text-success">{{ el.priceOfGoods }} рублей</p>	
			</a>
		</div>

		{% endfor %}
		

	</div>
	{% endfor %}
	</div>
</div>

{% endblock content %}

diplomProject/shop/templates/shopTemplates/register.html
{% extends 'base.html' %}

{% block content %}
<h2 class="text-center">Регистрация пользователя</h2>
<div class="row">
	<div class="col-md-12">
		<form method="POST">
			{% csrf_token%}
			{{form.as_p}}
			<button type="submit" class="btn btn-primary">Зарегистрироваться</button>
		</form>
	</div>
</div>
{% endblock content %}

diplomProject/shop/templates/shopTemplates/rezultSeach.html
{% extends 'base.html' %}
{% block title %}Результат поиска{% endblock title %}
{% block content %}
<h2 class="text-center text-succes">Результаты поиска</h2>
<div class="rezultDiv">
	{% for i in object_list %}
	<div class="col-md-6 col-xs-12 col-sm-6 goodDiv">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h4 class="text-center"><a href="{{ i.get_absolute_url }}">{{i.nameOfGoods}}</a></h4>
			</div>
			<div class="panel-body">
				<div class="media">
					<span class="pull-left"><img class="media-object goodPhoto" src="{{ i.imageGoods.url }}"
							alt="Нет фото"></span>
					<div class="media-body">
						<p>Цена: {{i.priceOfGoods}}</p>
						<p>Категория: {{i.categoryGoods}}</p>
						<p>Производитель: {{i.manufacturerOfGoods}}</p>
					</div>
				</div>
			</div>
			<div class="panel-footer">
				<p>{{i.contexOfGoods}}</p>
				<p>В продаже с: {{i.dateAppGoods}}</p>
			</div>
		</div>
	</div>
	{% empty %}
	<p>Во вашему запросу ничего не найдено</p>
	{% endfor %}
</div>
<div class="col-md-12">
	<div class="pagination">
		<span class="step-links">
			{% if page_obj.has_previous %}
			<a href="?page=1">Первая</a>
			<a href="?page={{ page_obj.previous_page_number }}">Предыдущая страница</a>
			{% endif %}

			<span class="current">
				Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
			</span>

			{% if page_obj.has_next %}
			<a href="?page={{ page_obj.next_page_number }}">Следующая страница</a>
			<a href="?page={{ page_obj.paginator.num_pages }}">Последняя страница</a>
			{% endif %}
		</span>
	</div>
{% endblock content %}

diplomProject/shop/templates/shopTemplates/sellerDetail.html
{% extends 'base.html' %}

{% block content %}
<h2 class="text-center">Личный кабинет пользователя {{user.get_username}}</h2>
<div class="row">
	<div class="col-md-12">
		{% if user.is_authenticated %}
		<p>Личный кабинет пользователя {{user.username}}</p>
		<p>{{userName1}}</p>
		<p>Номер id {{user.id}}</p>
		<p>Группа {{ user.groups.all.0 }}</p>
		{% endif %}
	</div>
</div>
{% for group in request.user.groups.all %}
	{% if group.name == 'Продавцы' %}
<div class="sallerMan">
	<p><a href="{% url 'showZakaz' %}">Заказы от покупателей</a></p>
	<p><a href="{% url 'addGood' %}">Добавить новый товар в ВАШ каталог</a></p>
	<h4 class="text-center text-success">Ваши товары в каталоге</h4>
	<div class="col-md-12">
	{% for i in object_list %}
	<div class="divGood">
	<p>Номер: {{i.id}}</p>
	<p>Название: {{i.nameOfGoods}}</p>
	<p>Цена: {{i.priceOfGoods}}</p>
	<p><img src="{{ i.imageGoods.url }}" alt="Фото товара"></p>
	<div class="withLink">
		<p><a href="editGoods/{{ i.id }}">Изменить товар</a></p>
		<p><a href="delete/{{ i.id }}">Удалить товар</a></p>
	</div>
	</div>
	{% empty %}
	<p>Товаров нет</p>
	</div>
	{% endfor %}
</div>
	{% endif %}
{% endfor %}
{% endblock content %}

diplomProject/shop/templates/shopTemplates/showZacaz.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h1 class="text-center">Заказы от покупателей</h1>
		</div>
	</div>
	<div class="col-md-12">
		<div class="flexBasket">
			<table class="table">
				<caption>Таблица заказов </caption>
				<thead>
					<tr>
						<th>Наименование</th>
						<th>Кол-во в заказе</th>
						<th>Цена за ед.</th>
						<th>Сумма</th>
						<th>Покупатель</th>
					</tr>
				</thead>
				{% for i in basket %}
				<tbody>
					<tr>
						<td>{{ i.goodsZacaz}}</td>
						<td>{{ i.countGoods}}</td>
						<td>{{ i.priceGoods}}</td>
						<td>{{ i }}</td>
						<td>{{ i.zakazGuman }}</td>
					</tr>
				</tbody>
				{% endfor %}
			</table>
		</div>
	</div>
</div>
{% endblock content %}